### ISSUE TITLE
Uncaught ReferenceError: vClickOutside is not defined

### ISSUE THREAD

**Issue by xy2z** [johndatserakis/vue-simple-context-menu#7]
https://jsfiddle.net/1m4c80uw/

Can't get it to work. Is there a simple non-node.js example?

**Comment by johndatserakis** [comment]
Hey sorry you're having trouble.

Yea for the browser version it looks like it's throwing `Uncaught ReferenceError: vClickOutside is not defined` as an error. The npm version is working fine though - so I'm going to take a look at the build process for the browser version and see if anything is causing that.

**Comment by johndatserakis** [comment]
Ok I got you - here's a new fiddle with a working browser example.

https://jsfiddle.net/johndatserakis/ay3zskmj/26/

I had to update the package because `vClickOutside` was not being properly included for the browser build. That's my bad.

As you can see in the example, I had to manually use the newest version of this library, `https://unpkg.com/vue-simple-context-menu/dist/vue-simple-context-menu.min.js`, because `unpkg.com` hasn't updated yet - as I just published the changes a few minutes ago.

Let me know how it goes for you.

**Comment by xy2z** [comment]
Great, thanks!
